name: reporter_html
description: An addon for the package `reporter`` that helps prepare html reports.
version: 0.0.1
repository: https://github.com/Bdaya-Dev/reporter/tree/main/packages/reporter_html

environment:
  sdk: ^3.0.6

dependencies:
  html: ">=0.15.4 <1.0.0"
  reporter: ">=0.1.0 <1.0.0"
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
