name: reporter_html
description: An addon for the package `reporter`` that helps prepare html reports.
version: 0.0.3
repository: https://github.com/Bdaya-Dev/reporter/tree/main/packages/reporter_html
topics:
  - reports
  - html
  - table
environment:
  sdk: ^3.0.6

dependencies:
  html: ">=0.15.4 <1.0.0"
  reporter: ^0.1.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
