name: reporter_html
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

dependencies:
  html: ^0.15.4
  reporter: ^0.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
