name: reporter_syncfusion_flutter_xlsio
description: An addon for the package `reporter` that uses `syncfusion_flutter_xlsio` to prepare excel reports.
version: 0.1.0
repository: https://github.com/Bdaya-Dev/reporter/tree/main/packages/reporter_syncfusion_flutter_xlsio

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_xlsio: ^22.2.7
  reporter: ^0.1.4
  collection: ^1.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
