name: _shared_addons
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.6

dependencies:
  reporter:
    path: ../reporter
  _shared:
    path: ../_shared


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
