name: reporter
description: A package that helps prepare tabular reports.
version: 0.1.3
repository: https://github.com/Bdaya-Dev/reporter/tree/main/packages/reporter
topics:
  - reports
  - table
environment:
  sdk: ^3.0.6

dependencies:
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  _shared:
    path: ../_shared/
  _shared_addons:
    path: ../_shared_addons/
