name: reporter
description: A package that helps prepare tabular reports.
version: 0.0.2
repository: https://github.com/Bdaya-Dev/reporter

environment:
  sdk: ^3.0.6

# dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  collection: ^1.18.0
